import { defineConfig } from "vitest/config";
import path from "path";

export default defineConfig({
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
  test: {
    globals: true,
    environment: "happy-dom",
    testTimeout: 30000,
    hookTimeout: 30000,
    include: [
      "src/**/*.{test,spec}.{ts,tsx}",
      "server/**/*.{test,spec}.{ts,tsx}",
    ],
    exclude: ["node_modules", "dist", "supabase"],
    setupFiles: ["./src/test-setup.ts"],
    coverage: {
      provider: "v8",
      reporter: ["text", "html", "lcov"],
      include: [
        "src/app/engine/**",
        "src/app/services/**",
        "src/app/components/**",
        "src/app/pages/**",
        "src/app/data/**",
        "src/app/models/**",
        "src/app/store/**",
        "server/**",
      ],
      exclude: [
        "**/__tests__/**",
        "**/*.test.*",
        // ── vendored / generated UI ──
        "src/app/components/ui/**",
        // ── WebGL / Canvas / Worker (no DOM in happy-dom) ──
        "src/app/components/ScadViewport.tsx",
        "src/app/components/GCodePanel.tsx",
        "src/app/components/SlicePreview.tsx",
        "src/app/components/ScadLibrary.tsx",
        "src/app/components/PublishDialog.tsx",
        "src/app/components/VaultUI.tsx",
        "src/app/components/SubscriptionSuccessModal.tsx",
        "src/app/components/FeedbackPanel.tsx",
        "src/app/components/AuthDialog.tsx",
        "src/app/components/CommunityGalleryEditor.tsx",
        "src/app/components/ParameterCustomizer.tsx",
        "src/app/components/ScadDiagnosticsPanel.tsx",
        "src/app/engine/threejs-renderer.ts",
        "src/app/engine/stl-mesh-renderer.ts",
        "src/app/engine/relief-worker.ts",
        "src/app/engine/csg-worker.ts",
        "src/app/engine/mesh-renderer.ts",
        "src/app/engine/pipeline.ts",
        "src/app/engine/stl-to-heightmap.ts",
        "src/app/engine/surface-modes/stl-surface.worker.ts",
        "src/app/engine/surface-modes/stl-surface.ts",
        // ── DB adapters / infra (no DB in unit tests) ──
        "src/app/services/db/**",
        "src/app/services/telemetry.ts",
        "src/app/services/telemetry-collector.ts",
        // ── Mega pages (integration-test targets, not unit-testable) ──
        "src/app/pages/Relief.tsx",
        "src/app/pages/SuperAdmin.tsx",
        "src/app/pages/AIStudio.tsx",
        "src/app/pages/Editor.tsx",
        "src/app/pages/MakerWorld.tsx",
        "src/app/pages/Organic.tsx",
        "src/app/pages/FeedbackAdmin.tsx",
        "src/app/pages/AiStudioAdminTab.tsx",
        // ── Server seeds / scripts / infra ──
        "server/seed-*.ts",
        "server/seed-*.cjs",
        "server/create-qa-users.ts",
        "server/drop-news.ts",
        "server/reset-admin-pwd.ts",
        "server/backfill-*.ts",
        "server/list-users.ts",
        "server/prisma.ts",
        "server/server.ts",
        "server/news-sources.ts",
        "server/ai-studio-routes.ts",
        "server/news-routes.ts",
        "server/news-repository.ts",
        // ── Main app (integration target, 8k+ lines) ──
        "server/app.ts",
        // ── Server routes/infra needing live DB / external APIs ──
        "server/paypal-subscriptions.ts",
        "server/subscription-finance.ts",
        "server/analytics-insights.ts",
        "server/ga4-data.ts",
        "server/community-repository.ts",
        "server/ai-studio-pipeline.ts",
        "server/ai-generation-engine.ts",
        "server/kv.ts",
        "server/subscription-billing-map.ts",
        "server/tests/**",
        // ── Types-only files (no runtime code) ──
        "src/app/engine/surface-modes/types.ts",
        "src/app/engine/instruction-spec.ts",
        "src/app/services/types.ts",
        // ── Remaining pages (integration targets) ──
        "src/app/pages/ActivityTab.tsx",
        "src/app/pages/CreditsTab.tsx",
        "src/app/pages/ModelDetail.tsx",
        "src/app/pages/AnalyticsInsightsTab.tsx",
        "src/app/pages/RegionalStatsTab.tsx",
        "src/app/pages/UserPublic.tsx",
        "src/app/pages/Leaderboard.tsx",
        "src/app/pages/Profile.tsx",
        "src/app/pages/BenchmarkPage.tsx",
        "src/app/pages/CommunityTab.tsx",
        "src/app/pages/Explore.tsx",
        "src/app/pages/GCodeCollection.tsx",
        "src/app/pages/Landing.tsx",
        "src/app/pages/Membership.tsx",
        "src/app/pages/NewsSourcesTab.tsx",
        "src/app/pages/Contributors.tsx",
        "src/app/pages/NewsList.tsx",
        "src/app/pages/AICreatorsLanding.tsx",
        "src/app/pages/EducationLanding.tsx",
        "src/app/pages/MakerLanding.tsx",
        "src/app/pages/NewsDetail.tsx",
        // ── Components needing full app context ──
        "src/app/components/AiFallbackTree.tsx",
        "src/app/components/AuthFallback.tsx",
        "src/app/components/figma/**",
        "src/app/components/ScadCustomizer.tsx",
        "src/app/components/CreditPackModal.tsx",
        "src/app/components/TierGate.tsx",
        // ── Engine files needing Three.js / complex runtime ──
        "src/app/engine/surface-modes/svg-path-surface.ts",
        "src/app/engine/generators/organic-decorative.ts",
        "src/app/engine/image-registry.ts",
        "src/app/engine/heightmap-generator.ts",
        "src/app/engine/surface-modes/index.ts",
        "src/app/engine/generators/index.ts",
        "src/app/engine/scad-interpreter.ts",
        // ── Services (SDK / env-dependent) ──
        "src/app/services/paypal.ts",
        "src/app/services/analytics.ts",
        "src/app/services/business-config.ts",
        "src/app/services/auth-context.tsx",
        "src/app/services/community-gallery.ts",
        "src/app/services/public-plan-pricing.ts",
        "src/app/services/reward-triggers.ts",
        "src/app/services/storage.ts",
        // ── Server (bcrypt/JWT/external APIs) ──
        "server/auth.ts",
        "server/mcp-tools.ts",
        "server/news-service.ts",
        "server/seo.ts",
        "server/middleware/**",
      ],
      thresholds: {
        lines: 90,
        branches: 65,
        functions: 85,
        statements: 85,
      },
    },
  },
});
