export type NewsSourceSeed = {
  id: string;
  slug: string;
  name: string;
  type: string;
  language: "es" | "en";
  baseUrl: string;
  feedUrl: string | null;
  listingUrl: string | null;
  fetchMode: "rss" | "atom" | "listing";
  enabled: boolean;
  priority: number; // Lower = higher priority. UY:10-19, LATAM:20-39, ES:40-49, US/World:50-99, Communities:100+
  editorialPolicy?: "standard" | "brief_only";
  editorialNotes?: string | null;
};

export const DEFAULT_NEWS_SOURCES: NewsSourceSeed[] = [
  // ── Priority 1: Uruguay ──
  {
    id: "ns_macrotec-uy",
    slug: "macrotec-uy",
    name: "Macrotec Uruguay",
    type: "news",
    language: "es",
    baseUrl: "https://www.macrotec.com.uy",
    feedUrl: null,
    listingUrl: "https://www.macrotec.com.uy/blog",
    fetchMode: "listing",
    enabled: true,
    priority: 10,
    editorialPolicy: "brief_only",
    editorialNotes: "Fuente comercial útil para radar local, pero suele producir piezas delgadas o tipo catálogo.",
  },
  {
    id: "ns_fabrix-uy",
    slug: "fabrix-uy",
    name: "Fabrix Uruguay",
    type: "news",
    language: "es",
    baseUrl: "https://fabrix.com.uy",
    feedUrl: null,
    listingUrl: "https://fabrix.com.uy/blogs/novedades",
    fetchMode: "listing",
    enabled: true,
    priority: 11,
    editorialPolicy: "brief_only",
    editorialNotes: "Catálogo y novedades de marca; mantener visible como radar breve y fuera de indexación.",
  },

  // ── Priority 2: Marcas globales relevantes (Creality, Bambu Lab) ──
  {
    id: "ns_creality-blog",
    slug: "creality-blog",
    name: "Creality Blog",
    type: "news",
    language: "en",
    baseUrl: "https://www.creality.com",
    feedUrl: null,
    listingUrl: "https://www.creality.com/blogs/news",
    fetchMode: "listing",
    enabled: true,
    priority: 15,
    editorialPolicy: "brief_only",
    editorialNotes: "Blog muy promocional. Conviene degradarlo a brief hasta que aparezcan piezas editoriales más sólidas.",
  },
  {
    id: "ns_bambulab-blog",
    slug: "bambulab-blog",
    name: "Bambu Lab Blog",
    type: "news",
    language: "en",
    baseUrl: "https://blog.bambulab.com",
    feedUrl: "https://blog.bambulab.com/rss/",
    listingUrl: "https://blog.bambulab.com/",
    fetchMode: "rss",
    enabled: true,
    priority: 16,
    editorialPolicy: "brief_only",
    editorialNotes: "Vendor blog — promotional signals mixed with product announcements. Keep as radar breve.",
  },

  // ── Priority 3: LATAM (Argentina, Chile, México) ──
  {
    id: "ns_3dnatives-es",
    slug: "3dnatives-es",
    name: "3Dnatives ES",
    type: "news",
    language: "es",
    baseUrl: "https://www.3dnatives.com",
    feedUrl: "https://www.3dnatives.com/es/feed/",
    listingUrl: "https://www.3dnatives.com/es/",
    fetchMode: "rss",
    enabled: true,
    priority: 20,
    editorialNotes: "Fuente editorial sólida en español con cobertura amplia de industria, materiales y hardware. Indexable.",
  },
  {
    id: "ns_impresoras3d-com",
    slug: "impresoras3d-com",
    name: "Impresoras3D.com",
    type: "news",
    language: "es",
    baseUrl: "https://www.impresoras3d.com",
    feedUrl: "https://www.impresoras3d.com/feed/",
    listingUrl: "https://www.impresoras3d.com/",
    fetchMode: "rss",
    enabled: true,
    priority: 25,
    editorialPolicy: "brief_only",
    editorialNotes: "Contenido predominantemente de catálogo y listados de producto con señal editorial delgada; mantener como radar breve.",
  },

  // ── Priority 4: España ──
  {
    id: "ns_3dwork-io",
    slug: "3dwork-io",
    name: "3DWork.io",
    type: "news",
    language: "es",
    baseUrl: "https://3dwork.io",
    feedUrl: "https://3dwork.io/feed/",
    listingUrl: "https://3dwork.io/",
    fetchMode: "rss",
    enabled: true,
    priority: 40,
    editorialNotes: "Cobertura maker/prosumer en español desde España. Buenos tutoriales y reviews de impresoras.",
  },

  // ── Priority 5: USA / World (English) ──
  {
    id: "ns_3dprint",
    slug: "3dprint",
    name: "3DPrint.com",
    type: "news",
    language: "en",
    baseUrl: "https://3dprint.com",
    feedUrl: "https://3dprint.com/feed/",
    listingUrl: "https://3dprint.com/",
    fetchMode: "rss",
    enabled: true,
    priority: 50,
    editorialNotes: "Líder de la industria en cobertura de noticias 3D en inglés. Alta señal editorial y cobertura de funding/launches.",
  },
  {
    id: "ns_3dprintingindustry",
    slug: "3d-printing-industry",
    name: "3D Printing Industry",
    type: "news",
    language: "en",
    baseUrl: "https://3dprintingindustry.com",
    feedUrl: "https://3dprintingindustry.com/feed/",
    listingUrl: "https://3dprintingindustry.com/",
    fetchMode: "rss",
    enabled: true,
    priority: 55,
    editorialNotes: "Cobertura profesional con fuerte foco en manufactura aditiva industrial, funding y partnerships.",
  },
  {
    id: "ns_fabbaloo",
    slug: "fabbaloo",
    name: "Fabbaloo",
    type: "news",
    language: "en",
    baseUrl: "https://www.fabbaloo.com",
    feedUrl: "https://www.fabbaloo.com/feed",
    listingUrl: "https://www.fabbaloo.com/",
    fetchMode: "rss",
    enabled: true,
    priority: 60,
    editorialNotes: "Análisis profundo de materiales, impresoras y workflows maker. Buen contenido evergreen.",
  },
  {
    id: "ns_develop3d",
    slug: "develop3d",
    name: "DEVELOP3D",
    type: "news",
    language: "en",
    baseUrl: "https://develop3d.com",
    feedUrl: "https://develop3d.com/feed/",
    listingUrl: "https://develop3d.com/",
    fetchMode: "rss",
    enabled: true,
    priority: 65,
    editorialNotes: "Foco en CAD/CAM/CAE profesional. Buena señal para software de diseño y manufactura aditiva industrial.",
  },
  {
    id: "ns_voxelmatters",
    slug: "voxelmatters",
    name: "VoxelMatters",
    type: "news",
    language: "en",
    baseUrl: "https://www.voxelmatters.com",
    feedUrl: "https://www.voxelmatters.com/feed/",
    listingUrl: "https://www.voxelmatters.com/",
    fetchMode: "listing",
    enabled: true,
    priority: 70,
    editorialPolicy: "brief_only",
    editorialNotes: "Fuente todavía ruidosa para indexación; mantener en radar breve hasta afinar scraper o moverla a feed más estable.",
  },
  {
    id: "ns_3dnatives",
    slug: "3dnatives",
    name: "3Dnatives EN",
    type: "news",
    language: "en",
    baseUrl: "https://www.3dnatives.com",
    feedUrl: "https://www.3dnatives.com/en/feed/",
    listingUrl: "https://www.3dnatives.com/en/",
    fetchMode: "rss",
    enabled: true,
    priority: 75,
    editorialNotes: "Versión EN de 3Dnatives. Mismo nivel editorial sólido que la versión ES; complementa cobertura global.",
  },

  // ── New high-quality sources ──
  {
    id: "ns_all3dp",
    slug: "all3dp",
    name: "All3DP",
    type: "news",
    language: "en",
    baseUrl: "https://all3dp.com",
    feedUrl: "https://all3dp.com/feed/",
    listingUrl: "https://all3dp.com/",
    fetchMode: "rss",
    enabled: true,
    priority: 52,
    editorialNotes: "Referente en guías, reviews y comparativas evergreen. Excelente señal editorial para contenido indexable y guías.",
  },
  {
    id: "ns_hackaday-3dp",
    slug: "hackaday-3dp",
    name: "Hackaday 3D Printing",
    type: "news",
    language: "en",
    baseUrl: "https://hackaday.com",
    feedUrl: "https://hackaday.com/category/3d-printers-hacks/feed/",
    listingUrl: "https://hackaday.com/category/3d-printers-hacks/",
    fetchMode: "rss",
    enabled: true,
    priority: 80,
    editorialNotes: "Comunidad hacker/maker con foco en hacks creativos de impresión 3D. Muy buena señal DIY y experimentación.",
  },

  // ── Communities (disabled by default) ──
  {
    id: "ns_makerworld-community",
    slug: "makerworld-community",
    name: "MakerWorld Community",
    type: "community",
    language: "en",
    baseUrl: "https://makerworld.com",
    feedUrl: null,
    listingUrl: "https://makerworld.com/en",
    fetchMode: "listing",
    enabled: false,
    priority: 110,
  },
  {
    id: "ns_printables-clubs",
    slug: "printables-clubs",
    name: "Printables Clubs",
    type: "community",
    language: "en",
    baseUrl: "https://www.printables.com",
    feedUrl: null,
    listingUrl: "https://www.printables.com/",
    fetchMode: "listing",
    enabled: false,
    priority: 120,
  },
  {
    id: "ns_thangs-content",
    slug: "thangs-content",
    name: "Thangs Content",
    type: "community",
    language: "en",
    baseUrl: "https://thangs.com",
    feedUrl: null,
    listingUrl: "https://thangs.com/",
    fetchMode: "listing",
    enabled: false,
    priority: 130,
  },
  {
    id: "ns_mmf-blog",
    slug: "myminifactory-blog",
    name: "MyMiniFactory Blog",
    type: "community",
    language: "en",
    baseUrl: "https://www.myminifactory.com",
    feedUrl: null,
    listingUrl: "https://www.myminifactory.com/blog",
    fetchMode: "listing",
    enabled: false,
    priority: 140,
  },
  {
    id: "ns_cults-blog",
    slug: "cults3d-blog",
    name: "Cults3D",
    type: "community",
    language: "en",
    baseUrl: "https://cults3d.com",
    feedUrl: null,
    listingUrl: "https://cults3d.com/en",
    fetchMode: "listing",
    enabled: false,
    priority: 150,
  },

  // ── Portuguese sources (BR) ──
  {
    id: "ns_impressao3dfacil",
    slug: "impressao3dfacil",
    name: "Impressão 3D Fácil",
    type: "news",
    language: "es", // PT content, mapped to ES for now until PT locale is supported in news
    baseUrl: "https://www.impressao3dfacil.com.br",
    feedUrl: "https://www.impressao3dfacil.com.br/feed/",
    listingUrl: "https://www.impressao3dfacil.com.br/",
    fetchMode: "rss",
    enabled: true,
    priority: 30,
    editorialPolicy: "brief_only",
    editorialNotes: "Principal portal brasileño de impresión 3D. Contenido en PT; marcar como brief_only hasta agregar soporte PT en noticias.",
  },
  {
    id: "ns_wish3d",
    slug: "wish3d-blog",
    name: "Wish 3D Blog",
    type: "news",
    language: "es",
    baseUrl: "https://www.wish3d.com.br",
    feedUrl: null,
    listingUrl: "https://www.wish3d.com.br/blog",
    fetchMode: "listing",
    enabled: true,
    priority: 31,
    editorialPolicy: "brief_only",
    editorialNotes: "E-commerce brasileño con blog técnico sobre impresión 3D. Contenido en PT; radar breve.",
  },

  // ── AI & Generative 3D ──
  {
    id: "ns_tomshardware-3dp",
    slug: "tomshardware-3dp",
    name: "Tom's Hardware 3D Printing",
    type: "news",
    language: "en",
    baseUrl: "https://www.tomshardware.com",
    feedUrl: "https://www.tomshardware.com/feeds/tag/3d-printing",
    listingUrl: "https://www.tomshardware.com/tag/3d-printing",
    fetchMode: "rss",
    enabled: true,
    priority: 53,
    editorialNotes: "Hardware mainstream con sección dedicada a 3D printing. Reviews técnicos de impresoras y filamentos con alta credibilidad.",
  },

  // ── Maker community (enabled) ──
  {
    id: "ns_prusa-blog",
    slug: "prusa-blog",
    name: "Prusa Blog",
    type: "news",
    language: "en",
    baseUrl: "https://blog.prusa3d.com",
    feedUrl: "https://blog.prusa3d.com/feed",
    listingUrl: "https://blog.prusa3d.com/",
    fetchMode: "rss",
    enabled: true,
    priority: 17,
    editorialPolicy: "brief_only",
    editorialNotes: "Blog oficial de Prusa Research. Mezcla de news, tutoriales y releases. Alta credibilidad maker pero es vendor blog.",
  },
];
